### ISSUE TITLE
pngs are black, avis don't read

### ISSUE THREAD

**Issue by reillydonovan** [KirillLykov/oni2avi#5]
Thanks for this package!
I've gotten it to work, kinda, at least it outputs .avi files and .png sequences from a .oni, but the pngs are all blank (black) and the .avis won't open.  My .oni file is not corrupt, it plays back thru a player I made in processing and is recognized by other OpenNI samples without corrupt error returns, any suggestions?  Mac OS Yosemite OpenNI v.1.5.7.10
 Also, by some off chance would you know how to bring a .oni into the Unity game engine and have it render the playback as a point cloud?  
Thanks!

**Comment by florianletsch** [comment]
Having the same issue. Both the `-img.avi` and `-depth.avi` are unplayable. Both files seem to be empty except for minimal information (file header?). Both files are exactly 414 bytes in size. Also, the files are created when the tool is still running, they don't seem to be written in the end, when conversion has finished. 

I have tried MPEG-1, MPEG-4 and FLV1 with no difference.

System is Mac OS El Capitan, 
Open CV 2.4.12
OpenNI 1.5.7.10

**Comment by KirillLykov** [comment]
Could you send me a oni file to check this behaviour (through dropbox/gdrive link or somehow)? Please, be sure that it is generated with the same version of OpenNI you are using to compile oni2avi.

**Comment by florianletsch** [comment]
Wow, really good catch. I'll try this once I get home tonight.

**Comment by florianletsch** [comment]
Yes, it worked. Thank you so much!
