### ISSUE TITLE
Build fails with error: redefinition of 'oss'

### ISSUE THREAD

**Issue by florianletsch** [KirillLykov/oni2avi#8]
Build fails with error: redefinition of 'oss'.

```
g++ -O2 -I/usr/local/include/ni -I/usr/local/include/opencv -I/usr/local/include -c oni2avi.cpp
oni2avi.cpp:231:21: error: redefinition of 'oss'
        std::ostringstream oss;
                           ^
oni2avi.cpp:216:28: note: previous definition is here
        std::ostringstream oss;
                           ^
1 error generated.
make: [oni2avi.o] Error 1 (ignored)
g++ -o oni2avi oni2avi.o -L/usr/local/lib -lOpenNI -lboost_system-mt -lboost_program_options-mt -lboost_filesystem-mt -lopencv_video -lopencv_highgui -lopencv_core -lopencv_imgproc -lopencv_contrib
clang: error: no such file or directory: 'oni2avi.o'
make: [oni2avi] Error 1 (ignored)
```

I have no idea about C++, but I moved the problematic line `std::ostringstream oss;` out of the for loop, so from line 216 to line 201:

```cpp
 try
    {
      std::ostringstream oss;
      for(size_t iframe = 0; iframe < nframes; ++iframe)
      {
```

Somehome, this fixed it. Maybe this is of help to anyone in the future.

![I have no idea what Im doing](https://s-media-cache-ak0.pinimg.com/736x/e1/10/e4/e110e4f1a25705c7f23974aac7e1cbc4.jpg)

**Comment by KirillLykov** [comment]
Good to know, this is due to the patch someone sent me and I didn't check it because of problems wih opencv. So I fixed compilation error by renaming oss. Should work
